### ISSUE TITLE
What's the download address of old firmware?

### ISSUE THREAD

**Issue by antonyw** [sunzj/Way_of_Downgrade_BOSE_QC35ii#3]
Such as BayWolf_2.5.1_acorn_coeffs_signed.xuv

**Comment by xxzbg** [comment]
Die Download-Adresse ist deutlich in der Mitte des Artikels angegeben. Bitte überprüfen Sie den Artikel erneut.

**Comment by xxzbg** [comment]
The download address is clearly written in the middle of the article. Please check the article again.

**Comment by antonyw** [comment]
> The download address is clearly written in the middle of the article. Please check the article again.

Thank you, I just missed it.
I'm going to try this way of downgread qc35ii, hope nothing goes wrong.
